## Base URL for the site
baseURL = 'https://boning-gu.github.io/'
## Site title
title = 'Gu Guoqin'
## Use hugo-brewm theme
theme = 'hugo-brewm'
## Enable Git information for pages
enableGitInfo = true
## Convert all URLs to absolute URLs
canonifyURLs = true
## Default language for content
defaultContentLanguage = 'en'
## Files to ignore when building site
ignoreFiles = [ '\.redacted', '\.old','\.bak', '\.tmp', '\.swp', '\.DS_Store']
## Generate a robots.txt
enableRobotsTXT = true

## Sitemap configuration
[sitemap]
    ## Change frequency setting (will affect posts listings layout): 'always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never'
    changeFreq = 'monthly'

## Front matter field configurations
[frontmatter]
    ## Publication date fields
    date = [':default']
    ## Expiry date fields
    expiryDate = ['expiryDate', 'unpublishdate', ':default']
    ## Last modified date fields
    lastmod = ['lastmod', ':default']

## Markup configuration
[markup]
    ## Table of contents settings
    [markup.tableOfContents]
        ## Minimum heading level to include
        startLevel = 2
        ## Maximum heading level to include
        endLevel = 3
        ## Use ordered list for TOC
        ordered = false

    ## Code highlighting settings
    [markup.highlight]
        ## Enable code fence highlighting
        codeFences = true
        ## Starting line number
        lineNoStart = 1
        ## Show line numbers
        lineNos = false
        ## Put line numbers in table
        lineNumbersInTable = true
        ## Use classes for styling
        noClasses = false
        ## Width of tab character
        tabWidth = 4

    ## Goldmark markdown processor settings
    [markup.goldmark]
        [markup.goldmark.renderer]
            ## Allow HTML in markdown
            unsafe = true

[outputs]
    home = ['html', 'rss', 'json']

## RSS configuration
[services.rss]
    ## Limit RSS item
    limit = -1

## Taxonomy configuration
[taxonomies]
    ## Category taxonomy
    category = "categories"
    ## Tag taxonomy
    tag = "tags"
    ## Series taxonomy
    series = "series"
    ## Author taxonomy
    author = "author"

## Site parameters
[params]
    ## Site title
    title = "Gu Guoqin"
    ## Site description
    description = "Personal website of Gu Guoqin - Economics student at Xiamen University, passionate about Financial Engineering and Data Analysis"
    ## Copyright notice
    copyright = "Copyright 2025 © Gu Guoqin"
    ## Enable extended metadata (social cards)
    extMeta = true
    ## Enable coffee metric
    coffeeStat = false
    ## Do not block AI user agent for robot.txt
    AllowAIRobots = false
    ## Minimize clutter for personal site
    ZenMode = false
    ## Disable Black background on main-footer
    DisableFootBar = false
    ## Merge site license, footer menu and coffee stat
    unifiedFooter = true

    ## Author information
    [params.author]
        ## site author's name
        name = 'Gu Guoqin'
        ## Author's email (will be used for RSS feed)
        email = 'guoqin_gu@163.com'

    ## Comments configuration
    [params.comments]
        ## Disable comments for personal site
        disabled = true

    ## Logo configuration
    [params.logo]
        ## Enable logo type
        logoType = true

    ## Feed display settings
    [params.feed]
        ## Enable flowlines
        flowlines = true
        ## Limit number of flowlines
        flowlinesLimit = 10
    
    ## Home page display settings
    [params.home]
        ## Enable slide carousel
        disableSlide = false
        ## Enable taxonomy listing carousel
        disableListing = false
        ## Select taxonomy listing to be featured
        featuredListing = ['categories', 'series']

    ## Post display settings
    [params.posts]
        ## Enable text justification
        justifying = false
        ## Disable paragraph indentation
        noIndent = false
        ## Use sans-serif fonts as default
        sfdefault = false
        ## Show colophon section (including QR code)
        colophon = true
        ## disable redaction history
        disableHistory = false
        ## Show related content
        related = true
        ## Show share buttons
        share = true

    ## Search configuration
    [params.search]
        ## Enable search functionality, please index your site first
        enabled = true
        ## Use pagefind search when javascript enabled, currently only 'pagefind' is supported, further options to be determined
        pagefind = true

## Menu configuration
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 10
    
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 20
    
    [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 30
    
    [[menu.main]]
        name = "Blog"
        url = "/posts/"
        weight = 40
    
    [[menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 50
